### ISSUE TITLE
not support node V12?

### ISSUE THREAD

**Issue by byte-voyager** [code-dot-org/artist#12]
```
3626 warn notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.3","npm":"6.14.6"})
3627 warn notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
3628 verbose notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
3628 verbose notsup Required: {"node":"<8.10.0"}
3628 verbose notsup Actual:   {"npm":"6.14.6","node":"12.16.3"}
3629 warn file-loader@1.1.6 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
3630 warn ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
3631 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
3632 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
3633 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3633 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
3633 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
3633 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3634 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
3635 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
3636 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3636 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
3636 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
3636 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3637 verbose stack Error: canvas@1.6.13 install: `node-gyp rebuild`
3637 verbose stack Exit status 1
3637 verbose stack     at EventEmitter.<anonymous> (/home/baloneo/software/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3637 verbose stack     at EventEmitter.emit (events.js:310:20)
3637 verbose stack     at ChildProcess.<anonymous> (/home/baloneo/software/nodejs/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3637 verbose stack     at ChildProcess.emit (events.js:310:20)
3637 verbose stack     at maybeClose (internal/child_process.js:1021:16)
3637 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
3638 verbose pkgid canvas@1.6.13
3639 verbose cwd /home/baloneo/下载/chrome-download/artist-main
3640 verbose Linux 5.4.0-45-generic
3641 verbose argv "/home/baloneo/software/nodejs/bin/node" "/home/baloneo/software/nodejs/bin/npm" "install"
3642 verbose node v12.16.3
3643 verbose npm  v6.14.6
3644 error code ELIFECYCLE
3645 error errno 1
3646 error canvas@1.6.13 install: `node-gyp rebuild`
3646 error Exit status 1
3647 error Failed at the canvas@1.6.13 install script.
3647 error This is probably not a problem with npm. There is likely additional logging output above.
3648 verbose exit [ 1, true ]
```

**Comment by byte-voyager** [comment]
solved
